import * as m from "mithril";
import { ClassComponent, CVnode } from "mithril";

import { Header } from "../components/header";
import { Footer } from "../components/footer";

export class HomeView implements m.ClassComponent<{}> {
  public view({ attrs }: CVnode<{}>) {
    return m(".page", [
      m(Header),
      m(".view", [
        m("h1", "Home"),
        m("p", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis porttitor mauris. Nunc in massa lorem. Fusce nec arcu sapien. In id pharetra tortor. Pellentesque est metus, elementum at libero suscipit, consectetur consequat diam. Aenean eget erat magna. Nunc diam diam, laoreet in libero a, pretium efficitur nunc. Cras quis dolor nisi. Donec accumsan malesuada orci. Curabitur a placerat risus, ut luctus enim. In viverra mauris nisl, vel dictum eros sodales vel. Nullam imperdiet ac justo vitae eleifend. Curabitur in rutrum quam. Mauris consequat, velit at placerat porttitor, tellus libero porta nulla, id tincidunt sapien erat vel metus. Nulla ornare, odio et tristique finibus, leo est pellentesque magna, at suscipit tellus turpis ac elit. Vivamus laoreet nunc quis rhoncus maximus."),
        m("p", "Suspendisse non ex rhoncus nisl vestibulum semper. Donec dignissim tempus mauris, vitae rhoncus nunc ultricies id. Fusce consequat massa in felis fermentum vulputate. Duis tortor orci, efficitur eget viverra sed, auctor eu ipsum. Quisque et risus a neque dictum blandit. Integer sit amet euismod felis, nec congue dui. Donec pellentesque ante a dapibus facilisis. Sed mollis et nibh non dictum. Nulla facilisi. Curabitur facilisis, metus eget sagittis vestibulum, libero velit dictum dui, eu ultrices odio enim sed nibh. Sed non ornare metus, in luctus orci."),
        m("p", "Nunc non odio vel diam ullamcorper pharetra. Praesent at nisl a ipsum blandit iaculis. Maecenas tempor molestie justo, id vehicula nisi fermentum vel. Quisque hendrerit tellus lectus, non porta mauris tempus at. Duis vel sollicitudin elit. Donec posuere dolor et mauris pulvinar finibus. Suspendisse nec odio vitae nibh accumsan rutrum et consequat massa. Duis feugiat justo vel massa tempus fringilla. Aenean id tincidunt justo. Aenean iaculis, enim eu sollicitudin vestibulum, nisi erat ullamcorper nunc, ut gravida ipsum dui a ante. Aliquam nec pharetra sem. Nunc in auctor metus, sit amet tempus nisl."),
        m("p", "Donec fermentum pharetra justo, volutpat euismod urna sagittis vel. Nullam neque enim, consectetur sed semper in, volutpat in urna. Vestibulum eu erat at enim sagittis hendrerit fermentum eget velit. In dignissim turpis eget magna vestibulum, sit amet rhoncus magna gravida. Suspendisse id euismod quam, quis dapibus eros. Nam commodo tempor nisl, nec pellentesque nibh convallis non. Sed euismod neque fringilla metus pellentesque ultricies. Duis sit amet suscipit purus. In hac habitasse platea dictumst. Aliquam congue dui id consectetur dapibus. Integer at lorem tristique, egestas arcu a, scelerisque lorem."),
        m("p", "Maecenas lectus justo, consectetur ac nunc vel, ullamcorper euismod lacus. Nunc in orci eget dui ullamcorper porttitor. Integer sed augue quis ligula dictum pharetra. Proin non mollis ex, vitae varius augue. Praesent finibus varius tellus vitae porta. Proin ipsum felis, sollicitudin sit amet laoreet quis, lacinia non sem. Phasellus quis finibus ligula, quis iaculis quam. Donec lacus ipsum, lacinia ut massa eget, fringilla finibus sem. Vestibulum et egestas lacus. Sed in bibendum diam. Nunc est leo, eleifend ac ipsum ut, interdum rhoncus est. Vestibulum molestie dignissim dictum."),
        m("p", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis porttitor mauris. Nunc in massa lorem. Fusce nec arcu sapien. In id pharetra tortor. Pellentesque est metus, elementum at libero suscipit, consectetur consequat diam. Aenean eget erat magna. Nunc diam diam, laoreet in libero a, pretium efficitur nunc. Cras quis dolor nisi. Donec accumsan malesuada orci. Curabitur a placerat risus, ut luctus enim. In viverra mauris nisl, vel dictum eros sodales vel. Nullam imperdiet ac justo vitae eleifend. Curabitur in rutrum quam. Mauris consequat, velit at placerat porttitor, tellus libero porta nulla, id tincidunt sapien erat vel metus. Nulla ornare, odio et tristique finibus, leo est pellentesque magna, at suscipit tellus turpis ac elit. Vivamus laoreet nunc quis rhoncus maximus."),
        m("p", "Suspendisse non ex rhoncus nisl vestibulum semper. Donec dignissim tempus mauris, vitae rhoncus nunc ultricies id. Fusce consequat massa in felis fermentum vulputate. Duis tortor orci, efficitur eget viverra sed, auctor eu ipsum. Quisque et risus a neque dictum blandit. Integer sit amet euismod felis, nec congue dui. Donec pellentesque ante a dapibus facilisis. Sed mollis et nibh non dictum. Nulla facilisi. Curabitur facilisis, metus eget sagittis vestibulum, libero velit dictum dui, eu ultrices odio enim sed nibh. Sed non ornare metus, in luctus orci."),
        m("p", "Nunc non odio vel diam ullamcorper pharetra. Praesent at nisl a ipsum blandit iaculis. Maecenas tempor molestie justo, id vehicula nisi fermentum vel. Quisque hendrerit tellus lectus, non porta mauris tempus at. Duis vel sollicitudin elit. Donec posuere dolor et mauris pulvinar finibus. Suspendisse nec odio vitae nibh accumsan rutrum et consequat massa. Duis feugiat justo vel massa tempus fringilla. Aenean id tincidunt justo. Aenean iaculis, enim eu sollicitudin vestibulum, nisi erat ullamcorper nunc, ut gravida ipsum dui a ante. Aliquam nec pharetra sem. Nunc in auctor metus, sit amet tempus nisl."),
        m("p", "Donec fermentum pharetra justo, volutpat euismod urna sagittis vel. Nullam neque enim, consectetur sed semper in, volutpat in urna. Vestibulum eu erat at enim sagittis hendrerit fermentum eget velit. In dignissim turpis eget magna vestibulum, sit amet rhoncus magna gravida. Suspendisse id euismod quam, quis dapibus eros. Nam commodo tempor nisl, nec pellentesque nibh convallis non. Sed euismod neque fringilla metus pellentesque ultricies. Duis sit amet suscipit purus. In hac habitasse platea dictumst. Aliquam congue dui id consectetur dapibus. Integer at lorem tristique, egestas arcu a, scelerisque lorem."),
        m("p", "Maecenas lectus justo, consectetur ac nunc vel, ullamcorper euismod lacus. Nunc in orci eget dui ullamcorper porttitor. Integer sed augue quis ligula dictum pharetra. Proin non mollis ex, vitae varius augue. Praesent finibus varius tellus vitae porta. Proin ipsum felis, sollicitudin sit amet laoreet quis, lacinia non sem. Phasellus quis finibus ligula, quis iaculis quam. Donec lacus ipsum, lacinia ut massa eget, fringilla finibus sem. Vestibulum et egestas lacus. Sed in bibendum diam. Nunc est leo, eleifend ac ipsum ut, interdum rhoncus est. Vestibulum molestie dignissim dictum."),
      ]),
      m(Footer),
    ]);
  }
}
